name: 'Install Requirements'
description: 'Install python requirements'
inputs:
  python-version:
    description: 'The Python version to use'
    required: true
    default: '3.10'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Upgrade PIP
      run: python -m pip install --upgrade pip
      shell: bash

    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash
