name: 'Create Release'
description: 'Create a GitHub release'
runs:
  using: 'composite'
  steps:
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: |
        gh release create -t "${{ inputs.release-title }}" ${{ inputs.release-tag }} --verify-tag  --generate-notes
      shell: bash

inputs:
  github-token:
    description: 'GitHub Token for authentication'
    required: true
  release-tag:
    description: "Tag to create release from"
    required: true
  release-title:
    description: 'Title of the release'
    required: true
  GH_TOKEN:
    description: 'GH token'
    required: true
