name: 'Prepare Icons'
description: 'Convert PNG to ICO for Windows and ICNS for macOS'
runs:
  using: 'composite'
  steps:
    - name: Convert PNG to ICO (Windows)
      run: |
        if [[ ${{ runner.os }} == 'Windows' ]]; then
          python -c "from PIL import Image; Image.open('images/logo.png').save('images/logo.ico')"
        fi
      shell: bash

    - name: Convert PNG to ICNS (macOS)
      run: |
        if [[ ${{ runner.os }} == 'macOS' ]]; then
          mkdir images/logo.iconset
          sips -z 16 16     images/logo.png --out images/logo.iconset/icon_16x16.png
          sips -z 32 32     images/logo.png --out images/logo.iconset/icon_16x16@2x.png
          sips -z 32 32     images/logo.png --out images/logo.iconset/icon_32x32.png
          sips -z 64 64     images/logo.png --out images/logo.iconset/icon_32x32@2x.png
          sips -z 128 128   images/logo.png --out images/logo.iconset/icon_128x128.png
          sips -z 256 256   images/logo.png --out images/logo.iconset/icon_128x128@2x.png
          sips -z 256 256   images/logo.png --out images/logo.iconset/icon_256x256.png
          sips -z 512 512   images/logo.png --out images/logo.iconset/icon_256x256@2x.png
          sips -z 512 512   images/logo.png --out images/logo.iconset/icon_512x512.png
          iconutil -c icns images/logo.iconset -o images/logo.icns
          rm -R images/logo.iconset
        fi
      shell: bash
