name: 'Upload Artifacts'
description: 'Upload build artifacts'
runs:
  using: 'composite'
  steps:
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}

inputs:
  artifact-name:
    description: 'Name of the artifact'
    required: true
  artifact-path:
    description: 'Path to the artifact'
    required: true
