name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      upload-url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: ./.github/actions/create-release
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-title: ${{ github.ref_name }}
          release-tag: ${{ github.ref_name }}

  upload-release:
    needs: prepare-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Restore cached artifacts
        id: 'cached-artifacts'
        uses: actions/cache/restore@v4
        with:
          path: dist/*
          key: '${{ runner.os }}-executable-${{ github.sha }}'

      - name: Upload Release Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref_name }} dist/${{ runner.os }}*
        shell: bash